# Site settings
title: One in a Trillion
description: Release notes & roadmap for the game.
url: https://carl-marc.github.io
baseurl: "/one-in-a-trillion" # Leave empty if not using a subdirectory

# Author settings
author:
  name: carl-marc

# Theme settings
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: pretty
