# Site settings
title: One in a Trillion
url: https://carl-marc.github.io
baseurl: "" # Leave empty if not using a subdirectory

# Author settings
author:
  name: carl-marc

# Theme settings
theme: jekyll-theme-cayman
github:
  is_project_page: false

# Build settings
markdown: kramdown
permalink: pretty
